### PR TITLE
systemtest: remove nested go module

### PR DESCRIPTION
**Pull request by axw**
The dependencies of systemtest are contained by apm-queue, so remove the nested module. This will allow Renovate to do its thing.

### CODE REVIEW

**Comment by marclop** [comment]
Won't this cause the `systemtest` to be run with `go test ./...` which are meant to run unit tests?

**Comment by axw** [comment]
@marclop oof, yeah :/

That seems like kind of an indirect way to stop `go test ./...` from running unnecessary tests though. I'll have have a think about how we can improve this.

**Comment by marclop** [comment]
the easiest way would be to modify the `test` Make target and use something like:

```
go test -race -v -timeout=$(GO_TEST_TIMEOUT) $(shell go list ./... | grep -v systemtest)
```

**Comment by axw** [comment]
@marclop I'm thinking of making the system tests opt-in, so we can also run `go test ./...` on our laptops easily. That would require running `go test -run-system-tests` when in the system test directory. Slightly more painful to run system tests on laptops, but I think not too bad. WDYT?

**Comment by marclop** [comment]
That seems a bit more friendly so we can keep using the `go test` commands directly without relying on the makefile necessarily.

**Review by marclop — APPROVED** [review]

**Pull request merged**
